-- MySQL Script generated by MySQL Workbench
-- Wed Oct 30 02:33:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema alonso_2_jdbc-patrones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alonso_2_jdbc-patrones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alonso_2_jdbc-patrones` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `alonso_2_jdbc-patrones` ;

-- -----------------------------------------------------
-- Table `alonso_2_jdbc-patrones`.`cuentas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alonso_2_jdbc-patrones`.`cuentas` ;

CREATE TABLE IF NOT EXISTS `alonso_2_jdbc-patrones`.`cuentas` (
  `idCuentas` INT(11) NOT NULL AUTO_INCREMENT,
  `numCuenta` VARCHAR(20) NULL DEFAULT NULL,
  `saldo` DOUBLE NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idCuentas`),
  UNIQUE INDEX `numCuenta_UNIQUE` (`numCuenta` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `alonso_2_jdbc-patrones`.`movimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alonso_2_jdbc-patrones`.`movimientos` ;

CREATE TABLE IF NOT EXISTS `alonso_2_jdbc-patrones`.`movimientos` (
  `idMovimientos` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `tipo` VARCHAR(1) NULL DEFAULT NULL,
  `importe` DOUBLE NULL DEFAULT NULL,
  `idCuentas` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idMovimientos`),
  INDEX `fk_Movimiento_1_idx_idx` (`idCuentas` ASC) VISIBLE,
  INDEX `fk_movimiento_1_idx` (`idCuentas` ASC) VISIBLE,
  CONSTRAINT `fk_movimiento_1`
    FOREIGN KEY (`idCuentas`)
    REFERENCES `alonso_2_jdbc-patrones`.`cuentas` (`idCuentas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
