-- MySQL Script generated by MySQL Workbench
-- Thu Nov 14 10:29:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema examenjdbc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema examenjdbc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `examenjdbc` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `examenjdbc` ;

-- -----------------------------------------------------
-- Table `examenjdbc`.`ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `examenjdbc`.`ingredientes` ;

CREATE TABLE IF NOT EXISTS `examenjdbc`.`ingredientes` (
  `idingredientes` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` CHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`idingredientes`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `examenjdbc`.`receta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `examenjdbc`.`receta` ;

CREATE TABLE IF NOT EXISTS `examenjdbc`.`receta` (
  `idreceta` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(250) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idreceta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `examenjdbc`.`recetaingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `examenjdbc`.`recetaingredientes` ;

CREATE TABLE IF NOT EXISTS `examenjdbc`.`recetaingredientes` (
  `idrecetaingredientes` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `idreceta` INT(11) NULL DEFAULT NULL,
  `idingrediente` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idrecetaingredientes`),
  INDEX `FK_receta_idx` (`idreceta` ASC) VISIBLE,
  INDEX `FK_ingrediente_idx` (`idingrediente` ASC) VISIBLE,
  CONSTRAINT `FK_ingrediente`
    FOREIGN KEY (`idingrediente`)
    REFERENCES `examenjdbc`.`ingredientes` (`idingredientes`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_receta`
    FOREIGN KEY (`idreceta`)
    REFERENCES `examenjdbc`.`receta` (`idreceta`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
