-- MySQL Script generated by MySQL Workbench
-- Wed Nov 13 20:51:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fincasytratamientos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fincasytratamientos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fincasytratamientos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fincasytratamientos` ;

-- -----------------------------------------------------
-- Table `fincasytratamientos`.`finca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fincasytratamientos`.`finca` ;

CREATE TABLE IF NOT EXISTS `fincasytratamientos`.`finca` (
  `idfinca` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idfinca`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fincasytratamientos`.`tratamientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fincasytratamientos`.`tratamientos` ;

CREATE TABLE IF NOT EXISTS `fincasytratamientos`.`tratamientos` (
  `idtratamientos` INT(11) NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(45) NULL DEFAULT NULL,
  `dosis` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idtratamientos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fincasytratamientos`.`relacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fincasytratamientos`.`relacion` ;

CREATE TABLE IF NOT EXISTS `fincasytratamientos`.`relacion` (
  `idrelacion` INT(11) NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `idfinca` INT(11) NULL DEFAULT NULL,
  `idtratamiento` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idrelacion`),
  INDEX `FK_finca_idx` (`idfinca` ASC) VISIBLE,
  INDEX `FK_tratamientos_idx` (`idtratamiento` ASC) VISIBLE,
  CONSTRAINT `FK_finca`
    FOREIGN KEY (`idfinca`)
    REFERENCES `fincasytratamientos`.`finca` (`idfinca`),
  CONSTRAINT `FK_tratamientos`
    FOREIGN KEY (`idtratamiento`)
    REFERENCES `fincasytratamientos`.`tratamientos` (`idtratamientos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
